#!/usr/bin/env python3
# Bigtreetech MMS G-code Preprocessor
# Based on Happy Hare MMU Preprocessor
#
# Copyright (C) 2026 Bigtreetech
#
# This file may be distributed under the terms of the GNU GPLv3 license.

import json
import logging, os, sys, re, time, argparse, shutil, traceback, tempfile, filecmp
from typing import (
    List,
    Dict,
    Any,
    Optional,
    Union
)

AUTHORZIED_SLICERS = ['PrusaSlicer', 'SuperSlicer', 'OrcaSlicer', 'BambuStudio']

MMS_FINGERPRINT = "; processed by MMS"
SLICER_REGEX = r"^;.*generated by ([a-z]*) .*$|^; (BambuStudio) .*$"
ORCASLICER_VERSION_REGEX = r"^;\s*generated by OrcaSlicer\s+(\d+(?:\.\d+){0,3})"

TOOL_DISCOVERY_REGEX = r"((^MMS_CHANGE_TOOL .*?TOOL=)|(^T))(?P<tool>\d{1,2})"

METADATA_TOOL_DISCOVERY = "!referenced_tools!"
METADATA_TOTAL_TOOLCHANGES = "!total_toolchanges!"

# PS/SS uses "extruder_colour", Orca uses "filament_colour"
COLORS_REGEX = {
    'PrusaSlicer' : r"^;\s*(?:extruder|filament)_colour\s*=\s*(#.*;*.*)$",
    'SuperSlicer' : r"^;\s*extruder_colour\s*=\s*(#.*;*.*)$",
    'OrcaSlicer'  : r"^;\s*filament_colour\s*=\s*(#.*;*.*)$",
    'BambuStudio' : r"^;\s*filament_colour\s*=\s*(#.*;*.*)$",
}
METADATA_COLORS = "!colors!"

TEMPS_REGEX = r"^;\s*(nozzle_)?temperature\s*=\s*(.*)$"
METADATA_TEMPS = "!temperatures!"

MATERIALS_REGEX = r"^;\s*filament_type\s*=\s*(.*)$"
METADATA_MATERIALS = "!materials!"

PURGE_VOLUMES_REGEX = r"^;\s*(flush_volumes_matrix|wiping_volumes_matrix)\s*=\s*(.*)$"
METADATA_PURGE_VOLUMES = "!purge_volumes!"

FILAMENT_NAMES_REGEX = r"^;\s*(filament_settings_id)\s*=\s*(.*)$"
METADATA_FILAMENT_NAMES = "!filament_names!"

# Detection for next pos processing
T_PATTERN  = r'^T(\d+)\s*(?:;.*)?$'
G1_PATTERN = r'^G[01](?=.*\sX(-?[\d.]+))(?=.*\sY(-?[\d.]+)).*$'

def gcode_processed_already(file_path):
    mmu_regex = re.compile(r"^" + MMS_FINGERPRINT, re.IGNORECASE)
    with open(file_path, 'r') as in_file:
        line = in_file.readline()
        return mmu_regex.match(line)

def _parse_version_tuple(version_str: str, parts: int = 3):
    if not version_str:
        return None
    m = re.match(r"^\s*(\d+(?:\.\d+)*)", version_str)
    if not m:
        return None
    nums = m.group(1).split(".")
    out = []
    for s in nums[:parts]:
        try:
            out.append(int(s))
        except ValueError:
            out.append(0)
    while len(out) < parts:
        out.append(0)
    return tuple(out)

def parse_gcode_file(file_path):
    slicer_regex = re.compile(SLICER_REGEX, re.IGNORECASE)
    orca_version_regex = re.compile(ORCASLICER_VERSION_REGEX, re.IGNORECASE)
    
    has_placeholders = False
    found_fields = set()
    slicer = None
    orca_version = None

    tools_used = set()
    total_toolchanges = 0
    colors = []
    temps = []
    materials = []
    purge_volumes = []
    filament_names = []

    with open(file_path, 'r') as in_file:
        for line in in_file:
            if not line.startswith(";"):
                continue
            if not slicer:
                match = slicer_regex.match(line)
                if match:
                    slicer = match.group(1) or match.group(2)
            if orca_version is None:
                mver = orca_version_regex.match(line)
                if mver:
                    orca_version = _parse_version_tuple(mver.group(1))

    if slicer in AUTHORZIED_SLICERS:
        tools_regex = re.compile(TOOL_DISCOVERY_REGEX, re.IGNORECASE)
        colors_regex = re.compile(COLORS_REGEX[slicer], re.IGNORECASE)
        temps_regex = re.compile(TEMPS_REGEX, re.IGNORECASE)
        materials_regex = re.compile(MATERIALS_REGEX, re.IGNORECASE)
        purge_volumes_regex = re.compile(PURGE_VOLUMES_REGEX, re.IGNORECASE)
        filament_names_regex = re.compile(FILAMENT_NAMES_REGEX, re.IGNORECASE)

        with open(file_path, 'r') as in_file:
            for line in in_file:
                if METADATA_TOOL_DISCOVERY in line or METADATA_TOTAL_TOOLCHANGES in line or \
                   METADATA_COLORS in line or METADATA_TEMPS in line or \
                   METADATA_MATERIALS in line or METADATA_PURGE_VOLUMES in line or \
                   METADATA_FILAMENT_NAMES in line:
                    has_placeholders = True

                match = tools_regex.match(line)
                if match:
                    tool = match.group("tool")
                    tools_used.add(int(tool))
                    total_toolchanges += 1

                if 'colors' not in found_fields:
                    match = colors_regex.match(line)
                    if match:
                        colors = [color.strip().lstrip('#') for color in match.group(1).split(';')]
                        found_fields.add('colors')

                if 'temps' not in found_fields:
                    match = temps_regex.match(line)
                    if match:
                        temps = re.split(';|,', match.group(2).strip())
                        found_fields.add('temps')

                if 'materials' not in found_fields:
                    match = materials_regex.match(line)
                    if match:
                        materials = match.group(1).strip().split(';')
                        found_fields.add('materials')

                if 'purge_volumes' not in found_fields:
                    match = purge_volumes_regex.match(line)
                    if match:
                        purge_volumes = [v.strip() for v in match.group(2).strip().split(',')]
                        found_fields.add('purge_volumes')

                if 'filament_names' not in found_fields:
                    match = filament_names_regex.match(line)
                    if match:
                        filament_names = [e.strip() for e in re.split(',|;', match.group(2).strip())]
                        found_fields.add('filament_names')

    return (has_placeholders, sorted(tools_used), total_toolchanges, colors, temps, materials, purge_volumes, filament_names, slicer)

def process_file(input_filename, output_filename, insert_nextpos, tools_used, total_toolchanges, colors, temps, materials, purge_volumes, filament_names):
    t_pattern = re.compile(T_PATTERN)
    g1_pattern = re.compile(G1_PATTERN)

    with open(input_filename, 'r') as infile, open(output_filename, 'w') as outfile:
        buffer = []
        tool = None
        outfile.write(f'{MMS_FINGERPRINT}\n')

        for line in infile:
            line = add_placeholder(line, tools_used, total_toolchanges, colors, temps, materials, purge_volumes, filament_names)
            if tool is not None:
                buffer.append(line)
                g1_match = g1_pattern.match(line)
                if g1_match:
                    x, y = g1_match.groups()
                    if insert_nextpos:
                        outfile.write(f'MMS_CHANGE_TOOL TOOL={tool} NEXT_POS="{x},{y}" ; T{tool}\n')
                    else:
                        outfile.write(f'MMS_CHANGE_TOOL TOOL={tool} ; T{tool}\n')
                    for buffered_line in buffer:
                        outfile.write(buffered_line)
                    buffer.clear()
                    tool = None
                continue

            t_match = t_pattern.match(line)
            if t_match:
                tool = t_match.group(1)
            else:
                outfile.write(line)

        if buffer:
            outfile.write(f'MMS_CHANGE_TOOL TOOL={tool} ; T{tool}\n')
            for line in buffer:
                outfile.write(line)

        outfile.write("; referenced_tools = %s\n" % ",".join(map(str, tools_used)))

def add_placeholder(line, tools_used, total_toolchanges, colors, temps, materials, purge_volumes, filament_names):
    if not line.startswith(";"):
        if METADATA_TOOL_DISCOVERY in line:
            line = line.replace(METADATA_TOOL_DISCOVERY, ",".join(map(str, tools_used)) if tools_used else "0")
        if METADATA_TOTAL_TOOLCHANGES in line:
            line = line.replace(METADATA_TOTAL_TOOLCHANGES, str(total_toolchanges))
        if METADATA_COLORS in line:
            line = line.replace(METADATA_COLORS, ",".join(map(str, colors)))
        if METADATA_TEMPS in line:
            line = line.replace(METADATA_TEMPS, ",".join(map(str, temps)))
        if METADATA_MATERIALS in line:
            line = line.replace(METADATA_MATERIALS, ",".join(map(str, materials)))
        if METADATA_PURGE_VOLUMES in line:
            line = line.replace(METADATA_PURGE_VOLUMES, ",".join(map(str, purge_volumes)))
        if METADATA_FILAMENT_NAMES in line:
            line = line.replace(METADATA_FILAMENT_NAMES, ",".join(map(str, filament_names)))
    return line

def main():
    parser = argparse.ArgumentParser(description="MMS G-Code Preprocessor")
    parser.add_argument("-f", "--filename", help="G-code file to parse")
    parser.add_argument("-p", "--path", help="Path for file")
    parser.add_argument("-m", "--placeholders", action='store_true', help="Process MMS placeholders")
    parser.add_argument("-n", "--nextpos", action='store_true', help="Add next position to tool change")
    args = parser.parse_args()

    if not args.filename:
        print("Filename required")
        sys.exit(-1)

    file_path = os.path.join(args.path or "", args.filename)
    if not os.path.isfile(file_path):
        print(f"File Not Found: {file_path}")
        sys.exit(-1)

    if gcode_processed_already(file_path):
        print(f"File already processed: {file_path}")
        return

    has_placeholder, tools_used, total_toolchanges, colors, temps, materials, purge_volumes, filament_names, slicer = parse_gcode_file(file_path)

    if args.nextpos or has_placeholder:
        with tempfile.TemporaryDirectory() as tmp_dir:
            tmp_file = os.path.join(tmp_dir, args.filename)
            process_file(file_path, tmp_file, args.nextpos, tools_used, total_toolchanges, colors, temps, materials, purge_volumes, filament_names)
            shutil.move(tmp_file, file_path)
            print(f"Successfully processed: {file_path}")
    else:
        print(f"No processing needed for: {file_path}")

if __name__ == "__main__":
    main()
